server:
  port: 9191
  contextPath: /sample-server

logging:
  level:
   org.springframework.security: DEBUG

spring:
  profiles: local
  datasource:
    url: "jdbc:mysql://localhost:3306/fsd"
    username: root
    password:
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USER}
    platform: mysql
    initialize: true
#  jpa:
#    database: MYSQL
#    hibernate:
#      ddl-auto: validate
