server:
  port: 9191
  contextPath: /sample-server

logging:
  file: myapplication.log
  level:
   org.springframework.security: DEBUG

security.basic.enabled: false
management.security.enabled: false

#spring.datasource.url = jdbc:mysql://localhost:3306/notes_app?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    password:
    url: "jdbc:mysql://demo-mysql:3306/fsd"
    username: root
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate