version: '3'

services:
  core-config:
    image: fsdapps/core-config-server:0.0.1-SNAPSHOT
    ports:
    - 9995:9995
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9995/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  demo-mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    volumes:
#    - mysql_data:/c/f/fsd/mysqlvolume
    restart: always

  sample-server:
    image: fsdapps/sample-server:0.0.1-SNAPSHOT
    depends_on:
      - demo-mysql
    ports:
    - 9191:9191
    environment:
      DATABASE_HOST: ${MYSQL_HOST}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_PORT: ${MYSQL_PORT}

