server:
  port: 9191
  contextPath: /sample-server

spring.data.mongodb.uri : mongodb://192.168.99.100:27017/local

kafka:
 producer:
  bootstrap: 192.168.99.100:9092
  topic: workunits

logging:
  file: myapplication.log
  level:
   org.springframework.security: DEBUG

#security.basic.enabled: false
#management.security.enabled: false

#spring.datasource.url = jdbc:mysql://localhost:3306/notes_app?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/fsd"
    username: root
    password:
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USER}
    platform: mysql
    initialize: true
#  jpa:
#    database: MYSQL
#    hibernate:
#      ddl-auto: validate
